export interface CategoryDefinition {
  name: string
  title: string
  description: string
  order: number
  isBlock?: boolean
}

export const EXAMPLE_CATEGORIES: CategoryDefinition[] = [
  {
    name: "accordion",
    title: "Accordion",
    description: "Collapsible stacked sections.",
    order: 1,
  },
  {
    name: "alert",
    title: "Alert",
    description: "Displays a callout for user attention, such as a success message, warning, or error.",
    order: 2,
    isBlock: true,
  },
  {
    name: "alert-dialog",
    title: "Alert Dialog",
    description: "Modal dialog for confirmations.",
    order: 3,
  },
  {
    name: "aspect-ratio",
    title: "Aspect Ratio",
    description: "Displays content at a fixed ratio.",
    order: 4,
  },
  {
    name: "autocomplete",
    title: "Autocomplete",
    description: "An input that suggests options as you type.",
    order: 5,
    isBlock: true,
  },
  {
    name: "avatar",
    title: "Avatar",
    description: "User profile images with fallbacks.",
    order: 6,
  },
  {
    name: "badge",
    title: "Badge",
    description: "Badges are used to highlight items, notify users, or display statuses.",
    order: 7,
    isBlock: true,
  },
  {
    name: "breadcrumb",
    title: "Breadcrumb",
    description: "Navigation path trail.",
    order: 8,
  },
  {
    name: "button",
    title: "Button",
    description: "Triggers an action or event.",
    order: 9,
  },
  {
    name: "button-group",
    title: "Button Group",
    description: "Grouped, adjacent buttons.",
    order: 10,
  },
  {
    name: "calendar",
    title: "Calendar",
    description: "Date picker calendar grid.",
    order: 11,
  },
  {
    name: "card",
    title: "Card",
    description: "Container for related content.",
    order: 12,
  },
  {
    name: "carousel",
    title: "Carousel",
    description: "Scrolling media showcase.",
    order: 13,
  },
  {
    name: "chart",
    title: "Chart",
    description: "Data visualization components.",
    order: 14,
  },
  {
    name: "checkbox",
    title: "Checkbox",
    description: "Binary selection control.",
    order: 15,
  },
  {
    name: "collapsible",
    title: "Collapsible",
    description: "Expandable content sections.",
    order: 16,
  },
  {
    name: "combobox",
    title: "Combobox",
    description: "Searchable single-select input.",
    order: 17,
  },
  {
    name: "command",
    title: "Command",
    description: "Command palette / quick search.",
    order: 18,
  },
  {
    name: "context-menu",
    title: "Context Menu",
    description: "Right-click action menus.",
    order: 19,
  },
  {
    name: "data-grid",
    title: "Data Grid",
    description: "A powerful TanStack Table v9 data grid with sorting, filtering, pagination, footer rows, drag-and-drop, virtualization, infinite scroll, row pinning, and tree rows.",
    order: 20,
    isBlock: true,
  },
  {
    name: "date-selector",
    title: "Date Selector",
    description: "A universal date selector component with multiple period types, filter modes, and flexible display options.",
    order: 21,
    isBlock: true,
  },
  {
    name: "dialog",
    title: "Dialog",
    description: "Modal overlay window.",
    order: 22,
  },
  {
    name: "drawer",
    title: "Drawer",
    description: "Slide-in side panel.",
    order: 23,
  },
  {
    name: "dropdown-menu",
    title: "Dropdown Menu",
    description: "Menu anchored to a trigger.",
    order: 24,
  },
  {
    name: "empty",
    title: "Empty",
    description: "Empty-state placeholder block.",
    order: 25,
  },
  {
    name: "event-calendar",
    title: "Event Calendar",
    description: "A headless-first event calendar with month, week, day, N-day and agenda views, drag-and-drop scheduling, recurring events, time zones, and an external CRUD contract.",
    order: 26,
    isBlock: true,
  },
  {
    name: "field",
    title: "Field",
    description: "Form field wrapper with label + error.",
    order: 27,
  },
  {
    name: "file-upload",
    title: "File Upload",
    description: "Enables users to upload files to a server or application.",
    order: 28,
  },
  {
    name: "filters",
    title: "Filters",
    description: "A comprehensive filtering system with multiple filter types, operators, and visual indicators for data organization.",
    order: 29,
    isBlock: true,
  },
  {
    name: "frame",
    title: "Frame",
    description: "Displays related content in a structured frame.",
    order: 30,
    isBlock: true,
  },
  {
    name: "gantt",
    title: "Gantt",
    description: "A headless-first gantt with split tree and timeline panes, day to year scales, zoom, drag and resize scheduling, progress, summary rollups, and an external CRUD contract.",
    order: 31,
    isBlock: true,
  },
  {
    name: "hover-card",
    title: "Hover Card",
    description: "Rich preview on hover.",
    order: 32,
  },
  {
    name: "icon-stack",
    title: "Icon Stack",
    description: "Shadcn Icon Stack for isometric icons, layered icon illustrations, and empty-state visuals.",
    order: 33,
    isBlock: true,
  },
  {
    name: "icon-tile",
    title: "Icon Tile",
    description: "Shadcn Icon Tile that wraps an icon in a consistent square surface for list rows, feature cards, and empty states.",
    order: 34,
    isBlock: true,
  },
  {
    name: "input",
    title: "Input",
    description: "Text entry field.",
    order: 35,
  },
  {
    name: "input-group",
    title: "Input Group",
    description: "Input with addons.",
    order: 36,
  },
  {
    name: "input-otp",
    title: "Input OTP",
    description: "One-time password entry.",
    order: 37,
  },
  {
    name: "item",
    title: "Item",
    description: "Generic list item slot.",
    order: 38,
  },
  {
    name: "kanban",
    title: "Kanban",
    description: "A drag-and-drop kanban component designed for seamless item organization across customizable columns.",
    order: 39,
    isBlock: true,
  },
  {
    name: "kbd",
    title: "Kbd",
    description: "Keyboard key styling.",
    order: 40,
  },
  {
    name: "label",
    title: "Label",
    description: "Field label.",
    order: 41,
  },
  {
    name: "menubar",
    title: "Menubar",
    description: "Horizontal application menu.",
    order: 42,
  },
  {
    name: "native-select",
    title: "Native Select",
    description: "Native select element.",
    order: 43,
  },
  {
    name: "navigation-menu",
    title: "Navigation Menu",
    description: "Top navigation menus.",
    order: 44,
  },
  {
    name: "number-field",
    title: "Number Field",
    description: "A numeric input element with increment and decrement buttons, and a scrub area.",
    order: 45,
    isBlock: true,
  },
  {
    name: "pagination",
    title: "Pagination",
    description: "Page navigation controls.",
    order: 46,
  },
  {
    name: "phone-input",
    title: "Phone Input",
    description: "A phone number input component with country selection and validation.",
    order: 47,
    isBlock: true,
  },
  {
    name: "popover",
    title: "Popover",
    description: "Floating content on click.",
    order: 48,
  },
  {
    name: "progress",
    title: "Progress",
    description: "Task completion bar.",
    order: 49,
  },
  {
    name: "radio-group",
    title: "Radio Group",
    description: "Single-select option group.",
    order: 50,
  },
  {
    name: "rating",
    title: "Rating",
    description: "A customizable star rating component that supports read-only display and interactive input modes.",
    order: 51,
    isBlock: true,
  },
  {
    name: "resizable",
    title: "Resizable",
    description: "Draggable panel splits.",
    order: 52,
  },
  {
    name: "scroll-area",
    title: "Scroll Area",
    description: "Custom scroll region.",
    order: 53,
  },
  {
    name: "scrollspy",
    title: "Scrollspy",
    description: "Dynamically highlights navigation to indicate current visible section in viewport during page scroll",
    order: 54,
    isBlock: true,
  },
  {
    name: "select",
    title: "Select",
    description: "Dropdown selection.",
    order: 55,
  },
  {
    name: "separator",
    title: "Separator",
    description: "Horizontal/vertical divider.",
    order: 56,
  },
  {
    name: "sheet",
    title: "Sheet",
    description: "Slide-over dialog.",
    order: 57,
  },
  {
    name: "skeleton",
    title: "Skeleton",
    description: "Loading placeholder.",
    order: 58,
  },
  {
    name: "slider",
    title: "Slider",
    description: "Range selection control.",
    order: 59,
  },
  {
    name: "sonner",
    title: "Sonner",
    description: "Toast notifications.",
    order: 60,
  },
  {
    name: "sortable",
    title: "Sortable",
    description: "A drag-and-drop sortable component designed for seamless item reordering with vertical, grid, and nested layouts.",
    order: 61,
    isBlock: true,
  },
  {
    name: "spinner",
    title: "Spinner",
    description: "Loading indicator.",
    order: 62,
  },
  {
    name: "stepper",
    title: "Stepper",
    description: "A step-by-step process for users to navigate through a series of steps.",
    order: 63,
    isBlock: true,
  },
  {
    name: "switch",
    title: "Switch",
    description: "Toggle control.",
    order: 64,
  },
  {
    name: "table",
    title: "Table",
    description: "Data table.",
    order: 65,
  },
  {
    name: "tabs",
    title: "Tabs",
    description: "Tabbed content panels.",
    order: 66,
  },
  {
    name: "textarea",
    title: "Textarea",
    description: "Multi-line text input.",
    order: 67,
  },
  {
    name: "timeline",
    title: "Timeline",
    description: "A visual representation of events in chronological order.",
    order: 68,
    isBlock: true,
  },
  {
    name: "toggle",
    title: "Toggle",
    description: "Pressed state control.",
    order: 69,
  },
  {
    name: "toggle-group",
    title: "Toggle Group",
    description: "Grouped toggle controls.",
    order: 70,
  },
  {
    name: "tooltip",
    title: "Tooltip",
    description: "Hover hints.",
    order: 71,
  },
  {
    name: "tree",
    title: "Tree",
    description: "A customizable tree component for React.",
    order: 72,
    isBlock: true,
  },
]
