packages:
  - "apps/*"
  - "packages/*"
  - "packages/registry/bases/*/components/*"
  - "packages/registry/bases/*/blocks/*"

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  esbuild: true
